name: tina_deskmate
description: Tina Desktop AI Companion
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  camera: ^0.11.0
  permission_handler: ^11.0.0
  http: ^1.2.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_tts: ^4.0.0
  flutter_local_notifications: ^18.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/faces/
    - assets/sounds/
